### ISSUE TITLE
zero eight five two, california might be blue

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [superwhiskers/pikafw#2]
-----BEGIN PGP MESSAGE-----
Version: Keybase OpenPGP v2.1.0
Comment: https://keybase.io/crypto

wcBMA3aSHPNCcQbLAQgAtPY4t3rQu+oGuoI21RfuLByGO6H7cFVY4zmpmH6qdX1x
eUvRSrwvfyM96OKsDm5UlBgYcmOH5qt553CXMRce6/iJ2haTnUGUex87FRNFLnPw
MfmglQZC5d/Wu2YyXPTUXDqopYQTdfdfwnweqJjPjwSuFs9kkaGc/fb8jOH/+2be
GT1p0qe4KHLb41keVKe6iMdGEVflGCafn3Z5rgyAjB+Ng7+TUO+FLHBXsJcv1m8s
dqjxGbNw1rZFHpKUjjadhRojvP/Jpjs6C5ErahIBSbFhoJKNsgj/yR4ok3FNaajE
VzLVm9drI00rfNBcj1Qt3OGZhb4xiftfxG0v9VeiPNKIATI4A+Jsj5Jf33x/OpuL
L1+ZhhMoaK/3p4P54s4SNeAxu1MLjVP12vzJG4qDFdFMI7WEMUsC6+mmZUyby8LR
F5JkQuS/Ik/x+k5i5UOdTiRINpCtaSsj3o5hi+KxPFqUa6dPDzXvlOtmkAkEwOrD
O/tcyzDJUlEko5iREGCmtJq0/OO61A36qA==
=FMNH
-----END PGP MESSAGE-----

**Comment by ThatNerdyPikachu** [comment]
obligatory @superwhiskers

**Comment by MikeModder** [comment]
I'm crying and shaking rn

**Comment by ThatNerdyPikachu** [comment]
find who owns the private key, I've given enough hints.

**Comment by SCOTT0852** [comment]
heck

**Comment by hyarsan** [comment]
hecky wecky indeed

**Comment by ThatNerdyPikachu** [comment]
@superwhiskers pls reopen

**Comment by superwhiskers** [comment]
sure!

**Comment by ThatNerdyPikachu** [comment]
-----BEGIN PGP MESSAGE-----
Version: Keybase OpenPGP v2.1.0
Comment: https://keybase.io/crypto

wcBMA3aSHPNCcQbLAQf/TtU8ysfVsWwJyU5MfeENqIIoW8ZlZbKOkEwisUK/zWhw
vDsj+v652FtlWhYLHVD5fs978QTM0Ark395gYMfpSJWowxmF1r8RU6Xx45n6kk5e
jbEFaRo+yot2u484NbdN3ieEANScgEm34pb5ao8uiqiEcSCG+bzepB3wRqI+fYL5
vqJ3nkezRG5PXQrJaA5ObYU7OwyBzmW38TTCr0YJHp8MDDvqaw/fepnhippIm74/
g1FnHmd2NlEO+EpKzTiqKrpZwYOi5JvgG/5yhIdY6ByEJzYbjMNgEoDOP/SvC44L
7Vj7CISUq5Ocf3WtOHweAdbWuUBp/MZjCynw6mempdKpAb/RS0lURDGD7tNFhqES
C4/9YDdL7oefolB/7jpALbEP09f85n6/nRvwfCJzw7nSqoT7aBpi+wcOb0CL+woL
5mIxiNx9HgcwCfb6alARgG1X1FhimfxqbostOWeewODmMYv9FrpVNguqt7ZdEhlz
Y42Z5tTK+PRheEgLf9f/D+PEg3yWCul/v7tRAtXpCNp0tWCj+jefeydcAXGkPlcu
tbdU1wt6eGtXXA==
=hDnh
-----END PGP MESSAGE-----

**Comment by SCOTT0852** [comment]
-----BEGIN PGP MESSAGE-----
Version: Keybase OpenPGP v2.1.0
Comment: https://keybase.io/crypto

wcFMA+pET/RfDqaOARAAsf9R3KP4rprKdaxVCZVc3oajL/Vl8LXMEOnR4ANaMish
Km0wEM48M8JOEQ/499DWqKYqCgmfdNQ8n5ChH/M/58dU9FGJxozhjLnDiDHtahIq
j00nOCky1Nlss/gsPEro2p/3KfOR6H+i/GIrRCZ8CytMpyAT/27U1lAyhBtlezt6
kzxf/Onte2OH1WrA4CHLyw5lxQrps2s1Pp0Vq6B1EBzuU6ffKXC6CCA2sgdbOlle
WApvVEAH31mDHZWReGhCeJXWDQGFZ1tkmZGtn3XOZ98DCQYv1Idq6v+/OXP9NPpd
CQtR62isQgjcmTR4WtDqK9ygFzP4hsaA+1YvORmlP45MZA3FgNCQREimqZLe8SL/
r9Twn3PB4FTzGXkdCHm3z+LYxzfdgUEKL0ge1u0vq2eoAXq7denGif2+q+6XdxIu
Qwylb4+dmOVHe3zYbXBazYcTg4HhocKXYdh628prAxVQQ4jZY2PrvMN0fueDefdo
0t713Q+zjidDnTHR7fdteQ5nKExzOupP0mnxDKbN/FFWpVVRsSOmj3ihq/uTcwuS
tO44whnLJV6D2G8MQTYILZ570q7ykku/ePgdrJB6eOa6np8KhgSyjYAxglGGTrzp
xTeTEMiJWlMrWMoSmrYZCVzhh78N7kh8T0Yb7liinBxviQwit2TFKAj35+mgczTS
fAHd5jwf9FspAGAk384SNIneJqIQ7YsuPUmz0RO6DrXKcmf8uzI3zlvmX+2ebaGZ
EkMG8TsR4zttRyEgE63kPodgnPIwXHupsuWj7+YhTiE33Y9EHi4D36JquxVpGr4E
OMxN0oH58O2R+mT4HRZwkndGmgQaxYZFywdMv/U=
=/iuV
-----END PGP MESSAGE-----

**Comment by MikeModder** [comment]
how do I unparticipate in an issue?

**Comment by SCOTT0852** [comment]
![image](https://user-images.githubusercontent.com/33875157/54961440-e9ff9d80-4f1d-11e9-8929-de802c753109.png)
